NotificationSystem.API/Models/ErrorViewModel.cs
using System;

namespace NotificationSystem.API.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NotificationSystem.API/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NotificationSystem.API.Models;


namespace NotificationSystem.API.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NotificationSystem.API/Controllers/NotificationChannelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NotificationSystem.ViewModel.ViewModels.NotificationChannelVM;


namespace NotificationSystem.API.Controllers
{
    public class NotificationChannelController : Controller
    {
        //Index Page View
        public IActionResult Index()
        {
            return View();
        }
    }
}

NotificationSystem.API/Controllers/NotificationEmailAlertController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NotificationSystem.ViewModel.ViewModels.NotificationEmailAlertVM;


namespace NotificationSystem.API.Controllers
{
    public class NotificationEmailAlertController : Controller
    {
        //Index Page View
        public IActionResult Index()
        {
            return View();
        }

    }
}

NotificationSystem.API/Controllers/NotificationSMSAlertController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NotificationSystem.ViewModel.ViewModels.NotificationSMSAlertVM;


namespace NotificationSystem.API.Controllers
{
    public class NotificationSMSAlertController : Controller
    {
        //index View Page
        public IActionResult Index()
        {
            return View();
        }

    }
}

NotificationSystem.API/Controllers/NotificationTemplateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NotificationSystem.ViewModel.ViewModels.NotificationTemplateVM;


namespace NotificationSystem.API.Controllers
{
    public class NotificationTemplateController : Controller
    {
        //Index Page View
        public IActionResult Index()
        {
            return View();
        }

        //Post Notification Get
        [HttpGet]
        public IActionResult PostNotification()
        {
            return View();
        }

        //Post Notification Post
        [HttpPost]
        public IActionResult PostNotification([FromBody] NotificationTemplateFormVM notificationTemplateFormVM)
        {
            return View();
        }
    }
}

NotificationSystem.API/Controllers/NotificationTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NotificationSystem.ViewModel.ViewModels.NotificationTypeVM;

namespace NotificationSystem.API.Controllers
{
    public class NotificationTypeController : Controller
    {
        //Index View
        public IActionResult Index()
        {
            return View();
        }

        //Get IActionResult
        [HttpGet]
        public IActionResult PostNotification()
        {
            return View();
        }

        //Post Method
        [HttpPost]
        public IActionResult PostNotification([FromBody] NotificationTypeFormVM notificationTypeFormVM)
        {
            return View();
        }
    }
}

NotificationSystem.API/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Notification System, SMS | Email | And More</p>
</div>

NotificationSystem.API/Views/NotificationChannel/Index.cshtml
@{
    ViewData["Title"] = " Notification Channel";
}


<link href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" rel="stylesheet" />

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>

<div class="container-fluid p-0">

    <div class="row">

        <div class="col-12 col-xl-12">
            <h2 class="card-title"><span style="font-size: 20px;"><strong>Notification Channel</strong></span></h2>
            <div class="card">
                <div class="card-header">
                    
                </div>
                <table id="tblNotificationChannel" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Jet Li</td>
                            <td>lorem ipson the description of the email notification is displayed</td>
                        </tr>
                        <tr>
                            <td>Mohammed Ali</td>
                            <td>lorem ipson the description of the email notification is displayed</td>
                        </tr>
                        <tr>
                            <td>Bruce Lee</td>
                            <td>lorem ipson the description of the email notification is displayed</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div>
                <a class="btn btn-primary" asp-controller="Home" asp-action="Index">Back To HomePage</a>
            </div>
        </div>

    </div>

</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#tblNotificationChannel').DataTable();
    });
</script>

NotificationSystem.API/Views/NotificationEmailAlert/Index.cshtml
@{
    ViewData["Title"] = " Notification Email Alert";
}


<link href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" rel="stylesheet" />

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>

<div class="container-fluid p-0">

    <div class="row">

        <div class="col-12 col-xl-12">
            <h2 class="card-title"><span style="font-size: 20px;"><strong>Email Notification</strong></span></h2>
            <div class="card">
                <div class="card-header">
                    
                </div>
                <table id="tblNotificationEmail" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Email</th>
                            <th>Subject</th>
                            <th>Message</th>
                            <th>Receiver Name</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>

                        <tr>
                            <td>Johnsonblack@yahoo.com</td>
                            <td>Internship Role</td>
                            <td>I wish to apply for the role of a software developer at your sweet reputable firm, please accept me!</td>
                            <td>James Rodriguez</td>
                            <td class="table-action">
                                <a href="#"><i class="align-middle" style="color:blue" data-feather="edit-2"></i></a>
                            </td>
                        </tr>
                        <tr>
                            <td>Emiliarice@yahoo.com</td>
                            <td>Internship Role</td>
                            <td>I wish to apply for the role of a software developer at your sweet reputable firm, please accept me!</td>
                            <td>Jason Vorhez</td>
                            <td class="table-action">
                                <a href="#"><i class="align-middle" style="color:blue" data-feather="edit-2"></i></a>
                            </td>
                        </tr>
                        <tr>
                            <td>clarkville@yahoo.com</td>
                            <td>Internship Role</td>
                            <td>I wish to apply for the role of a software developer at your sweet reputable firm, please accept me!</td>
                            <td>Jonny Bravo</td>
                            <td class="table-action">
                                <a href="#"><i class="align-middle" style="color:blue" data-feather="edit-2"></i></a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#tblNotificationEmail').DataTable();
    });
</script>

NotificationSystem.API/Views/NotificationSMSAlert/Index.cshtml
@{
    ViewData["Title"] = " Notification SMS Alert";
}


<link href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" rel="stylesheet" />

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>

<div class="container-fluid p-0">

    <div class="row">

        <div class="col-12 col-xl-12">
            <h2 class="card-title"><span style="font-size: 20px;"><strong>SMS Notification</strong></span></h2>
            <div class="card">
                <div class="card-header">
                    
                </div>
                <table id="tblNotificationSMS" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Mobile No.</th>
                            <th>Subject</th>
                            <th>Message</th>
                            <th>Receiver Name</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>

                        <tr>
                            <td>+2347076379753</td>
                            <td>Manager Role</td>
                            <td>I wish to apply for the role of a System Analyst at your sweet reputable firm, please accept me!</td>
                            <td>James Rodriguez</td>
                            <td class="table-action">
                                <a href="#"><i class="align-middle" style="color:blue" data-feather="edit-2"></i></a>
                            </td>
                        </tr>
                        <tr>
                            <td>+2347076379753</td>
                            <td>Internship Role</td>
                            <td>I wish to apply for the role of a software developer at your sweet reputable firm, please accept me!</td>
                            <td>Jason Vorhez</td>
                            <td class="table-action">
                                <a href="#"><i class="align-middle" style="color:blue" data-feather="edit-2"></i></a>
                            </td>
                        </tr>
                        <tr>
                            <td>+2347076379753</td>
                            <td>Branch Manager</td>
                            <td>I wish to apply for the role of a software developer at your sweet reputable firm, please accept me!</td>
                            <td>Jonny Bravo</td>
                            <td class="table-action">
                                <a href="#"><i class="align-middle" style="color:blue" data-feather="edit-2"></i></a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#tblNotificationSMS').DataTable();
    });
</script>

NotificationSystem.API/Views/NotificationTemplate/Index.cshtml
@{
    ViewData["Title"] = " Notification Template";
}


<link href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" rel="stylesheet" />

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>

<div class="container-fluid p-0">

    <div class="row">

        <div class="col-12 col-xl-12">
            <h2 class="card-title"><span style="font-size: 20px;"><strong>Notification Template</strong></span></h2>
            <div class="card">
                <div class="card-header">
                    <a class="btn btn-primary" asp-controller="NotificationTemplate" asp-action="PostNotification">Add Notification Template</a>
                    <br />
                </div>
                <table id="tblNotificationTemplate" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Notification Type</th>
                            <th>Notification Channel</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>

                        <tr>
                            <td>Mike Tyson</td>
                            <td>lorem ipson the description of the email notification is displayed</td>
                            <td>Email</td>
                            <td>Email Channel</td>
                            <td class="table-action">
                                <a href="#"><i class="align-middle" style="color:blue" data-feather="edit-2"></i></a>
                                <a href="#"><i class="align-middle" style="color:red" data-feather="trash"></i></a>
                            </td>
                        </tr>
                        <tr>
                            <td>Mohammed Ali</td>
                            <td>lorem ipson the description of the email notification is displayed</td>
                            <td>Email</td>
                            <td>Email Channel</td>
                            <td class="table-action">
                                <a href="#"><i class="align-middle" style="color:blue" data-feather="edit-2"></i></a>
                                <a href="#"><i class="align-middle" style="color:red" data-feather="trash"></i></a>
                            </td>
                        </tr>
                        <tr>
                            <td>Bruce Lee</td>
                            <td>lorem ipson the description of the email notification is displayed</td>
                            <td>SMS</td>
                            <td>SMS Channel</td>
                            <td class="table-action">
                                <a href="#"><i class="align-middle" style="color:blue" data-feather="edit-2"></i></a>
                                <a href="#"><i class="align-middle" style="color:red" data-feather="trash"></i></a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#tblNotificationTemplate').DataTable();
    });
</script>

NotificationSystem.API/Views/NotificationTemplate/PostNotification.cshtml
@{
    ViewData["Title"] = " Notification Template";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" />
<style>
    label {
        padding-bottom: 20px;
    }

    i {
        position: absolute;
        visibility: hidden;
    }

    .success input {
        border-color: #2ecc71;
    }

    .error textarea {
        border-color: #e74e3c;
    }

    .success textarea {
        border-color: #2ecc71;
    }

    .error input {
        border-color: #e74e3c;
    }

    small {
        margin-left: 20px;
        visibility: hidden;
    }

    .success i.fa-check-circle {
        color: #2ecc71;
        visibility: visible;
        margin-top: 6px
    }

    .error i.fa-exclamation-circle {
        color: #e74e3c;
        visibility: visible;
        margin-top: 6px
    }

    .error small {
        color: #e74e3c;
        visibility: visible;
    }

    .success small {
        color: #2ecc71;
        visibility: visible;
    }
</style>

<div class="col-12 col-xl-12">
    <h2 class="card-title mb-3"><span style="font-size: 20px;"><strong>Add Notification Template</strong></span></h2>
    <div class="card">
        <div class="card-header">
        </div>
        <div class="card-body">
            <form id="form">
                <div class="mb-3 row">
                    <label class="col-form-label col-sm-2 text-sm-right">Name</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" placeholder="Full Name" id="name">
                        <i class="fas fa-check-circle"></i>
                        <i class="fas fa-exclamation-circle"></i>
                        <small>Error Message</small>
                    </div>
                </div>
                <div class="mb-3 row">
                    <label class="col-form-label col-sm-2 text-sm-right">Description</label>
                    <div class="col-sm-10">
                        <textarea class="form-control" placeholder="Description" id="description" rows="3"></textarea>
                        <i class="fas fa-check-circle"></i>
                        <i class="fas fa-exclamation-circle"></i>
                        <small>Error Message</small>
                    </div>
                </div>
                <div class="mb-3 row">
                    <label class="col-form-label col-sm-2 text-sm-right">Notification Type</label>
                    <div class="col-sm-10">
                        <select class="form-control" id="notifType">
                            <option>Select Notification Type</option>
                            <option>Welcome Message</option>
                            <option>Application Submission</option>
                            <option>Application Approval</option>
                        </select>
                        <i class="fas fa-check-circle"></i>
                        <i class="fas fa-exclamation-circle"></i>
                        <small>Error Message</small>
                    </div>
                </div>
                <div class="mb-3 row">
                    <label class="col-form-label col-sm-2 text-sm-right">Notification Channel</label>
                    <div class="col-sm-10">
                        <select class="form-control" id="notifChannel">
                            <option>Select Notification Channel</option>
                            <option>Email Channel</option>
                            <option>SMS Channel</option>
                        </select>
                        <i class="fas fa-check-circle"></i>
                        <i class="fas fa-exclamation-circle"></i>
                        <small>Error Message</small>
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-sm-10 ml-sm-auto">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    const form = document.getElementById('form');
    const name = document.getElementById('name');
    const notifType = document.getElementById('notifType');
    const notifChannel = document.getElementById('notifChannel');
    const description = document.getElementById('description');

    form.addEventListener('submit', (e) => {
        e.preventDefault();

        checkInputs();
    });

    function checkInputs() {
        //get the values from the inputs
        const nameValue = name.value.trim();
        const notifTypeValue = notifType.value.trim();
        const notifChannelValue = notifChannel.value.trim();
        const descriptionValue = description.value.trim();

        if (nameValue == "") {
            //show error and add erro class
            setErrorFor(name, "Input Field Cannot Be Blank");
        } else {
            //show the success class
            setSuccessFor(name, "Input Is Valid");
        }

        if (descriptionValue == "") {
            //show error and add erro class
            setErrorFor(description, "Input Field Cannot Be Blank");
        } else {
            //show the success class
            setSuccessFor(description, "Input Is Valid");
        }

        if (notifTypeValue == "Select Notification Type") {
            //show error and add erro class
            setErrorFor(notifType, "Input Field Cannot Be Blank");
        } else {
            //show the success class
            setSuccessFor(notifType, "Input Is Valid");
        }

        if (notifChannelValue == "Select Notification Channel") {
            //show error and add erro class
            setErrorFor(notifChannel, "Input Field Cannot Be Blank");
        } else {
            //show the success class
            setSuccessFor(notifChannel, "Input Is Valid");
        }
    }

    function setErrorFor(input , message) {
        const formControl = input.parentElement;
        const grandParent = formControl.parentElement;
        const small = formControl.querySelector('small');

        //add error message inside small tag
        small.innerText = message;

        //add error class
        grandParent.className = "mb-3 row error";
    }

    function setSuccessFor(input, message) {
        const formControl = input.parentElement;
        const grandParent = formControl.parentElement;
        const small = formControl.querySelector('small');

        //add success message inside small tag
        small.innerText = message;

        //add error class
        grandParent.className = "mb-3 row success";
    }

</script>

NotificationSystem.API/Views/NotificationType/Index.cshtml
@{
    ViewData["Title"] = " Notification Type";
}


<link href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" rel="stylesheet" />

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>

<div class="container-fluid p-0">

    <div class="row">

        <div class="col-12 col-xl-12">
            <h2 class="card-title"><span style="font-size: 20px;"><strong>Notification Type</strong></span></h2>
            <div class="card">
                <div class="card-header">
                    <a class="btn btn-primary" asp-controller="NotificationType" asp-action="PostNotification">Add Notification Type</a>
                    <br />
                </div>

                <table id="tblNotificationType" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Jackie Chan</td>
                            <td>lorem ipson the description of the email notification is displayed</td>
                            <td class="table-action">
                                <a href="#"><i class="align-middle" style="color:blue" data-feather="edit-2"></i></a>
                                <a href="#"><i class="align-middle" style="color:red" data-feather="trash"></i></a>
                            </td>
                        </tr>
                        <tr>
                            <td>Toby Maguire</td>
                            <td>lorem ipson the description of the email notification is displayed</td>
                            <td class="table-action">
                                <a href="#"><i class="align-middle" style="color:blue" data-feather="edit-2"></i></a>
                                <a href="#"><i class="align-middle" style="color:red" data-feather="trash"></i></a>
                            </td>
                        </tr>
                        <tr>
                            <td>Hashirama Senju</td>
                            <td>lorem ipson the description of the email notification is displayed</td>
                            <td class="table-action">
                                <a href="#"><i class="align-middle" style="color:blue" data-feather="edit-2"></i></a>
                                <a href="#"><i class="align-middle" style="color:red" data-feather="trash"></i></a>
                            </td>
                        </tr>
                        <tr>
                            <td>Pein Nagato</td>
                            <td>lorem ipson the description of the email notification is displayed</td>
                            <td class="table-action">
                                <a href="#"><i class="align-middle" style="color:blue" data-feather="edit-2"></i></a>
                                <a href="#"><i class="align-middle" style="color:red" data-feather="trash"></i></a>
                            </td>
                        </tr>
                        <tr>
                            <td>Sunade Senju</td>
                            <td>lorem ipson the description of the email notification is displayed</td>
                            <td class="table-action">
                                <a href="#"><i class="align-middle" style="color:blue" data-feather="edit-2"></i></a>
                                <a href="#"><i class="align-middle" style="color:red" data-feather="trash"></i></a>
                            </td>
                        </tr>
                        <tr>
                            <td>Hashirama Senju</td>
                            <td>lorem ipson the description of the email notification is displayed</td>
                            <td class="table-action">
                                <a href="#"><i class="align-middle" style="color:blue" data-feather="edit-2"></i></a>
                                <a href="#"><i class="align-middle" style="color:red" data-feather="trash"></i></a>
                            </td>
                        </tr>
                        <tr>
                            <td>Hashirama Senju</td>
                            <td>lorem ipson the description of the email notification is displayed</td>
                            <td class="table-action">
                                <a href="#"><i class="align-middle" style="color:blue" data-feather="edit-2"></i></a>
                                <a href="#"><i class="align-middle" style="color:red" data-feather="trash"></i></a>
                            </td>
                        </tr>
                        <tr>
                            <td>Hashirama Senju</td>
                            <td>lorem ipson the description of the email notification is displayed</td>
                            <td class="table-action">
                                <a href="#"><i class="align-middle" style="color:blue" data-feather="edit-2"></i></a>
                                <a href="#"><i class="align-middle" style="color:red" data-feather="trash"></i></a>
                            </td>
                        </tr>
                    </tbody>
                </table>

            </div>
        </div>

    </div>

</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#tblNotificationType').DataTable();
    });
</script>